/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_MyClass */

#ifndef _Included_com_company_MyClass
#define _Included_com_company_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_MyClass
 * Method:    stringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_company_MyClass_stringFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_company_MyClass
 * Method:    intFromC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_company_MyClass_intFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_company_MyClass
 * Method:    stringToC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_company_MyClass_stringToC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_company_MyClass
 * Method:    intToC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_company_MyClass_intToC
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
